export const sampleTradespeople = [
  {
    id: '1',
    name: 'Marcus Thompson',
    profession: 'Handyman',
    category: 'handyman',
    location: 'Oakwood Heights',
    phone: '(555) 123-4567',
    email: 'marcus@example.com',
    recommendationCount: 47,
    avgRating: 4.9,
    isVerified: true,
    specialties: ['Furniture Assembly', 'Minor Repairs', 'Drywall', 'Painting'],
    bio: 'Reliable handyman with over 15 years of experience. I treat every home like my own.',
    recommendations: [
      { id: 'r1', author: 'Sarah M.', date: '2024-01-15', text: 'Marcus fixed our leaky faucet and repaired the deck railing in one visit. Excellent work!', rating: 5 },
      { id: 'r2', author: 'James L.', date: '2024-01-10', text: 'Very professional and reasonably priced. Highly recommend for any household repairs.', rating: 5 },
      { id: 'r3', author: 'Emily R.', date: '2024-01-05', text: 'Third time using Marcus. Always punctual and thorough.', rating: 5 },
    ],
  },
  {
    id: '2',
    name: 'Elena Rodriguez',
    profession: 'Plumber',
    category: 'plumber',
    location: 'Riverside Commons',
    phone: '(555) 234-5678',
    email: 'elena@example.com',
    recommendationCount: 32,
    avgRating: 4.8,
    isVerified: true,
    specialties: ['Emergency Repairs', 'Water Heaters', 'Drain Cleaning', 'Pipe Installation'],
    bio: 'Licensed master plumber specializing in residential services. Available for emergencies.',
    recommendations: [
      { id: 'r4', author: 'Michael K.', date: '2024-01-12', text: 'Elena came out on a Sunday for our emergency. Fair pricing and excellent work.', rating: 5 },
      { id: 'r5', author: 'Linda P.', date: '2024-01-08', text: 'Installed our new water heater efficiently. Very knowledgeable.', rating: 5 },
    ],
  },
  {
    id: '3',
    name: 'David Chen',
    profession: 'Electrician',
    category: 'electrician',
    location: 'Maple Grove',
    phone: '(555) 345-6789',
    email: 'david@example.com',
    recommendationCount: 28,
    avgRating: 4.7,
    isVerified: true,
    specialties: ['Panel Upgrades', 'Lighting', 'Smart Home', 'Rewiring'],
    bio: 'Certified electrician focused on safety and quality. Specializing in modern smart home installations.',
    recommendations: [
      { id: 'r6', author: 'Nancy W.', date: '2024-01-14', text: 'David installed our whole-home smart lighting system. Works perfectly!', rating: 5 },
      { id: 'r7', author: 'Robert H.', date: '2024-01-06', text: 'Very thorough inspection and explained everything clearly.', rating: 4 },
    ],
  },
  {
    id: '4',
    name: 'Patricia Williams',
    profession: 'Painter',
    category: 'painter',
    location: 'Oakwood Heights',
    phone: '(555) 456-7890',
    email: 'patricia@example.com',
    recommendationCount: 41,
    avgRating: 4.9,
    isVerified: true,
    specialties: ['Interior Painting', 'Exterior Painting', 'Wallpaper', 'Cabinet Refinishing'],
    bio: 'Detail-oriented painter with an eye for color. Transforming homes one room at a time.',
    recommendations: [
      { id: 'r8', author: 'Karen B.', date: '2024-01-11', text: 'Patricia painted our entire first floor. The attention to detail was incredible.', rating: 5 },
      { id: 'r9', author: 'Tom S.', date: '2024-01-03', text: 'Clean work, protected all furniture. Very professional.', rating: 5 },
    ],
  },
  {
    id: '5',
    name: 'Anthony Brown',
    profession: 'HVAC Technician',
    category: 'hvac',
    location: 'Riverside Commons',
    phone: '(555) 567-8901',
    email: 'anthony@example.com',
    recommendationCount: 23,
    avgRating: 4.6,
    isVerified: false,
    specialties: ['AC Repair', 'Heating Systems', 'Duct Cleaning', 'Maintenance'],
    bio: 'Keeping homes comfortable year-round. Prompt service and honest assessments.',
    recommendations: [
      { id: 'r10', author: 'Susan D.', date: '2024-01-09', text: 'Fixed our AC quickly during the heat wave. Lifesaver!', rating: 5 },
    ],
  },
  {
    id: '6',
    name: 'Jennifer Martinez',
    profession: 'Landscaper',
    category: 'landscaper',
    location: 'Maple Grove',
    phone: '(555) 678-9012',
    email: 'jennifer@example.com',
    recommendationCount: 35,
    avgRating: 4.8,
    isVerified: true,
    specialties: ['Garden Design', 'Lawn Care', 'Tree Trimming', 'Irrigation'],
    bio: 'Creating beautiful outdoor spaces that thrive. Sustainable landscaping advocate.',
    recommendations: [
      { id: 'r11', author: 'Mark T.', date: '2024-01-13', text: 'Jennifer redesigned our backyard. It is now our favorite place to relax.', rating: 5 },
      { id: 'r12', author: 'Lisa G.', date: '2024-01-07', text: 'Regular lawn maintenance has never been better. Very reliable.', rating: 5 },
    ],
  },
]

export const neighborhoods = [
  'Oakwood Heights',
  'Riverside Commons',
  'Maple Grove',
  'Downtown',
  'Westside',
  'Northgate',
]
